apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-app
  labels:
    app: batch-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-app
  template:
    metadata:
      labels:
        app: batch-app
    spec:
      containers:
        - name: batch-app
          command:
          - java
          - -jar
          - /metering/batch.jar
          image: "localhost/batch:latest"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: 0.5
              memory: 512
          tty: true
          stdin: true
          serviceAccount: default
      terminationGracePeriodSeconds: 5
      automountServiceAccountToken: false
