apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marc-wkc-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

